name: Fetch Weather Data

on:
  schedule:
    - cron: '*/5 * * * *'  # mỗi 5 phút
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install requests
        run: pip install requests

      - name: Run fetch script
        run: python fetch_and_log.py

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/history.json
          git commit -m "Update weather data" || echo "No changes"
          git push
